#!/bin/sh
# Gives me tips on when I am lost on commands
# Includes nice header and subheader formatting!

# Usage:
# `what`: (no arguments) give entire list of help
# `what {term}`: search for term (similar to grep), but gives the context of the term (WIP)
# `what {term}` 1: greps for term 

python $HELPSCRIPT $HELP $@
